config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('newsletter.urls', 'newsletter'), namespace='newsletter')),
    path('', include(('article.urls', 'article'), namespace='article')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from newsletter.views import MailListView, MailDetailView, MailCreateView, MailUpdateView, MailDeleteView, \
    ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    HomePageView, MessageCreateView, MessageDetailView, MessageDeleteView, MessageUpdateView, LogAttemptListView
from newsletter.apps import NewsletterConfig
app_name = NewsletterConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),

    path('mail/', MailListView.as_view(), name="mail_list"),
    path('mail/<int:pk>/', MailDetailView.as_view(), name="mail_detail"),
    path('mail/create/', MailCreateView.as_view(), name="mail_create"),
    path('mail/update/<int:pk>/', MailUpdateView.as_view(), name='mail_update'),
    path('mail/delete/<int:pk>/', MailDeleteView.as_view(), name='mail_delete'),

    path('client/', ClientListView.as_view(), name="client_list"),
    path('client/<int:pk>/', ClientDetailView.as_view(), name="client_detail"),
    path('client/create/', ClientCreateView.as_view(), name="client_create"),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    path('message/', MessageListView.as_view(), name="message_list"),
    path('message/<int:pk>/', MessageDetailView.as_view(), name="message_detail"),
    path('message/create/', MessageCreateView.as_view(), name="message_create"),
    path('message/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('mail/<int:mail_pk>/logs/', LogAttemptListView.as_view(), name='log_list'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
app_name = UsersConfig.name

from django.urls import path
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView, UsersListView, \
    toggle_activiti

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='token'),
    path('reset-password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('list/', UsersListView.as_view(), name='user_list'),
    path('toggle_activiti/<int:pk>', toggle_activiti, name='toggle_activiti')

]

newsletter/models.py
from django.utils import timezone
from django.utils.translation import gettext as _
from django.db import models
from config import settings


NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    """ Клиент """
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=20, verbose_name='Отчество', **NULLABLE)
    email = models.EmailField(verbose_name='Электронный адрес')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.first_name}{self.last_name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    """ Сообщение """
    message_title = models.CharField(max_length=100, verbose_name='Тема письма')
    message_content = models.TextField(verbose_name='Содержание')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.message_title}'

    class Meta:
        verbose_name = 'Сообщение для рассылки'
        verbose_name_plural = 'Сообщения для рассылки'


class Mail(models.Model):
    """ Рассылка """

    class PeriodicityOfMail(models.TextChoices):
        ONCE_DAY = "Раз в день", _("Раз в день")
        ONCE_WEEK = "Раз в неделю", _("Раз в неделю")
        ONCE_MONTH = "Раз в месяц", _("Раз в месяц")

    class StatusOfMail(models.TextChoices):
        CREATED = "Создана", _("Создана")
        LAUNCHED = "Запущена", _("Запущена")
        FINISHED = "Завершена", _("Завершена")

    title = models.CharField(max_length=100, verbose_name='Тема рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    client = models.ManyToManyField(Client, verbose_name='Клиент', related_name='client')
    mail_datetime = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    mail_datetime_last = models.DateTimeField(default=timezone.now, verbose_name='Следующая отправка', **NULLABLE)
    mail_periodicity = models.CharField(verbose_name='Периодичность', choices=PeriodicityOfMail, default=PeriodicityOfMail.ONCE_DAY)
    mail_status = models.CharField(verbose_name='Статус отправки', choices=StatusOfMail, default=StatusOfMail.CREATED)
    mail_active = models.BooleanField(verbose_name='Активность рассылки', default=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.mail_status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('set_deactivate', 'Can deactivate mail'),
            ('view_all_mail', 'Can view all mail'),
        ]


class LogAttempt(models.Model):
    """Попытка рассылки"""
    class StatusOfLogAttempt(models.TextChoices):
        SUCCESS = "Успешно", _("Успешно")
        FAILED = "Безуспешно", _("Безуспешно")

    attempt_datetime = models.DateTimeField(verbose_name='Дата и время последней попытки', auto_now_add=True)
    attempt_status = models.CharField(max_length=50, choices=StatusOfLogAttempt, verbose_name="Cтатус попытки")
    server_response = models.CharField(verbose_name="Ответ почтового сервера", **NULLABLE)
    mail = models.ForeignKey(Mail, verbose_name="Рассылка", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.mail}, {self.attempt_datetime}, {self.attempt_status}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

newsletter/forms.py
from newsletter.models import Mail, Client, Message
from users.forms import StyleFormMixin
from django import forms


class MailForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mail
        exclude = ('mail_status', 'mail_active', 'owner')


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)


class MailManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mail
        fields = ('mail_active',)

newsletter/views.py
from audioop import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from newsletter.forms import MailForm, ClientForm, MessageForm, MailManagerForm
from newsletter.models import Mail, Client, Message, LogAttempt
from newsletter.services import get_random_articles_cache


class HomePageView(TemplateView):
    template_name = 'newsletter/home.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        mailing = Mail.objects.all()
        clients = Client.objects.all()
        context['count_mail'] = mailing.count()
        context['mail_is_active'] = mailing.filter(mail_active=True).count()
        context['count_client'] = clients.count()
        context['count_client_unique'] = clients.values('email').distinct().count()
        context['random_article_list'] = get_random_articles_cache(3)
        return context


class MailListView(LoginRequiredMixin, ListView):
    """ Просмотр списка рассылок """
    model = Mail

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moderator').exists():
            queryset = queryset.filter(owner=user)
        return queryset


class MailDetailView(LoginRequiredMixin, DetailView):
    """ Просмотр деталей рассылки """
    model = Mail

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moderator').exists() and user != self.object.owner:
            raise PermissionDenied
        return self.object


class MailCreateView(LoginRequiredMixin, CreateView):
    """ Создание рассылки """
    model = Mail
    form_class = MailForm
    success_url = reverse_lazy('newsletter:mail_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        form.fields['client'].queryset = Client.objects.filter(owner=user)
        form.fields['message'].queryset = Message.objects.filter(owner=user)
        return form

    def form_valid(self, form):
        mail = form.save()
        user = self.request.user
        mail.owner = user
        mail.save()
        return super().form_valid(form)


class MailUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактирование данных рассылки """
    model = Mail
    success_url = reverse_lazy('newsletter:mail_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            form.fields['client'].queryset = Client.objects.filter(owner=user)
            form.fields['message'].queryset = Message.objects.filter(owner=user)
        return form

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailForm
        elif user.groups.filter(name='moderator').exists():
            return MailManagerForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if (not user.is_superuser and user != self.object.owner and
                not user.groups.filter(name='moderator').exists()):
            raise PermissionDenied
        return self.object


class MailDeleteView(LoginRequiredMixin, DeleteView):
    """ Удаление рассылки """
    model = Mail
    success_url = reverse_lazy('newsletter:mail_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        return self.object


class ClientListView(LoginRequiredMixin, ListView):
    """ Просмотр списка клиентов """
    model = Client

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if not user.is_superuser:
            queryset = queryset.filter(owner=user)
        return queryset


class ClientDetailView(LoginRequiredMixin, DetailView):
    """Просмотр одного клиента"""
    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        return self.object


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Создание клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование данных клиента"""
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('newsletter:client_detail', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление клиента"""
    model = Client
    success_url = reverse_lazy('newsletter:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        return self.object


class MessageListView(LoginRequiredMixin, ListView):
    """ Просмотр списка сообщений """
    model = Message

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        user = self.request.user
        if not user.is_superuser:
            queryset = queryset.filter(owner=user)
        return queryset


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Просмотр деталей сообщения"""
    model = Message

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        return self.object


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Создание сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('newsletter:message_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('newsletter:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление сообщения"""
    model = Message
    success_url = reverse_lazy('newsletter:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        return self.object


class LogAttemptListView(LoginRequiredMixin, ListView):
    """Контроллер просмотра логов рассылки"""
    model = LogAttempt

    def get_queryset(self, *args, **kwargs):
        mail_pk = self.kwargs.get('mail_pk')
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(mail__pk=mail_pk)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['mail_pk'] = self.kwargs.get('mail_pk')
        return context

    def dispatch(self, request, *args, **kwargs):
        mail_pk = self.kwargs.get('mail_pk')
        user = self.request.user
        if not user.is_superuser and not Mail.objects.filter(pk=mail_pk, owner=user).exists():
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

newsletter/templates/newsletter/base.html
<!doctype html>
{% load static %}
<html lang="ru" class=" h-100" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>

<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-300 p-3 mx-auto flex-column">
    {% include 'newsletter/includes/inc_menu.html'%}
    {% block content %}
    {% endblock %}
    <footer class="mt-auto text-white-50"></footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

newsletter/templates/newsletter/client_confirm_delete.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Хотите удалить клиента: <i>{{object.last_name}} {{object.first_name}}?</i></h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-dark">Подтвердить</button>
                        <a href="{% url 'newsletter:client_list' %}" type="button" class="btn btn-success">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

newsletter/templates/newsletter/client_detail.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ client.last_name }} {{ client.first_name }}</h3>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Адрес электронной почты: {{client.email}}</li>
                        <li>Комментарий: {{client.comment}}</li>
                    </ul>
                    <a href="{% url 'newsletter:client_update' object.pk %}" type="button" class="btn btn-block btn-outline-dark">Редактировать</a>
                    <a href="{% url 'newsletter:client_delete' object.pk %}" type="button" class="btn btn-block btn-outline-danger">Удалить</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newsletter/templates/newsletter/client_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if object %}
                <h4 class="my-0 font-weight-normal">Редактировать клиента</h4>
                {% else %}
                <h4 class="my-0 font-weight-normal">Добавление клиента</h4>
                {% endif %}
            </div>
            <div class="card-body">
                {{form.as_p}}
                {% csrf_token %}
                {% if object %}
                <button type="submit" class="btn btn-block btn-outline-success form-control">Сохранить</button>
                {% else %}
                <button type="submit" class="btn btn-block btn-outline-success form-control">Добавить</button>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/client_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<body>
<h1>Список клиентов</h1>
<a href="{% url 'newsletter:client_create' %}" type="button" class="col-3 my-4 btn btn-outline-success">Создать клиента</a>
<table class="table" cellpadding="10" border="1" width="100%">
    <col width="20%">
    <col width="20%">
    <col width="60%">
    <thead>
    <tr>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Электронный адрес</th>
    </tr>
    </thead>
</table>
{% for object in object_list %}
<table class="table" cellpadding="10" border="1" width="100%">
    <col width="20%">
    <col width="20%">
    <col width="60%">
    <tbody>
    <tr>
        <td><a href="{% url 'newsletter:client_detail' object.pk %}">{{object.last_name}}</a></td>
        <td>{{object.first_name}}</td>
        <td>{{object.email}}</td>
    </tr>
    </tbody>
</table>
{% endfor %}
</body>
{% endblock %}

newsletter/templates/newsletter/logattempt_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<a href="{% url 'newsletter:mail_detail' mail_pk %}" class="col-4 btn btn-outline-info btn-block mb-3">
  Вернуться к рассылке
</a>
<table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Название рассылки</th>
      <th scope="col">Дата и время отправки</th>
      <th scope="col">Статус</th>
      <th scope="col">Ответ сервера</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ object.mail }}</td>
      <td>{{ object.attempt_datetime}}</td>
      <td>{{ object.attempt_status}}</td>
      <td>{{ object.server_response}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

newsletter/templates/newsletter/mail_confirm_delete.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Хотите удалить рассылку: <i>{{object.title}}?</i></h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-dark">Подтвердить</button>
                        <a href="{% url 'newsletter:mail_list' %}" type="button" class="btn btn-success">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

newsletter/templates/newsletter/mail_detail.html
{% extends 'newsletter/base.html' %}
{% block content %}
{% load user_tags %}
<div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ mail.title }}</h3>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Сообщение: {{mail.message}}</li>
                        <li>Периодичность: {{mail.mail_periodicity}}</li>
                        <li>Дата начала отправки рассылки: {{mail.mail_datetime}}</li>
                        <li>Дата отправки последней рассылки: {{mail.mail_datetime_last}}</li>
                    </ul>
                    {% if user == object.owner or user.is_superuser or user|is_moderator %}
                    <a href="{% url 'newsletter:mail_update' object.pk %}"
                       class="btn btn-block btn-outline-dark">Редактировать</a>
                    {% endif %}
                    {% if user == object.owner or user.is_superuser %}
                    <a href="{% url 'newsletter:mail_delete' object.pk %}"
                       class="btn btn-block btn-outline-danger">Удалить</a>
                    <a href="{% url 'newsletter:log_list' object.pk %}"
                    class="btn btn-outline-warning btn-block">Посмотреть лог</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newsletter/templates/newsletter/mail_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if object %}
                <h4 class="my-0 font-weight-normal">Редактировать рассылку</h4>
                {% else %}
                <h4 class="my-0 font-weight-normal">Добавьте рассылку</h4>
                {% endif %}
            </div>
            <div class="card-body">
                {{form.as_p}}
                {% csrf_token %}
                {% if object %}
                <button type="submit" class="btn btn-block btn-outline-success form-control">Сохранить</button>
                {% else %}
                <button type="submit" class="btn btn-block btn-outline-success form-control">Создать</button>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/mail_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<body>
<h1>Список рассылок</h1>
<a href="{% url 'newsletter:mail_create' %}" type="button" class="col-3 my-3 btn btn-outline-success">Создать рассылку</a>
<table class="table" cellpadding="10" border="1" width="100%">
    <col width="60%">
    <col width="20%">
    <col width="20%">
    <thead>
    <tr>
        <th scope="col">Название</th>
        <th scope="col">Периодичность</th>
        <th scope="col">Статус</th>
    </tr>
    </thead>
</table>
{% for object in object_list %}
<table class="table" cellpadding="10" border="1" width="100%">
    <col width="60%">
    <col width="20%">
    <col width="20%">
    <tbody>
    <tr>
        <td><a href="{% url 'newsletter:mail_detail' object.pk %}">{{object.title}}</a></td>
        <td>{{object.mail_periodicity}}</td>
        <td>{{object.mail_status}}</td>
    </tr>
    </tbody>
</table>
{% endfor %}
</body>
{% endblock %}

newsletter/templates/newsletter/message_confirm_delete.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Хотите удалить сообщение: <i>{{object.message_title}}?</i></h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark">Подтвердить</button>
                        <a href="{% url 'newsletter:message_list' %}" type="button" class="btn btn-success">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

newsletter/templates/newsletter/message_detail.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ message.message_title }}</h3>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Содержание: {{message.message_content}}</li>
                    </ul>
                    <a href="{% url 'newsletter:message_update' object.pk %}" type="button" class="btn btn-block btn-outline-dark">Редактировать</a>
                    <a href="{% url 'newsletter:message_delete' object.pk %}" type="button" class="btn btn-block btn-outline-danger">Удалить</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newsletter/templates/newsletter/message_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                {% if object %}
                <h4 class="my-0 font-weight-normal">Редактировать сообщение</h4>
                {% else %}
                <h4 class="my-0 font-weight-normal">Добавить сообщение</h4>
                {% endif %}
            </div>
            <div class="card-body">
                {{form.as_p}}
                {% csrf_token %}
                {% if object %}
                <button type="submit" class="btn btn-block btn-outline-success form-control">Сохранить</button>
                {% else %}
                <button type="submit" class="btn btn-block btn-outline-success form-control">Добавить</button>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/message_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<body>
<h1>Список сообщений для рассылки</h1>
<a href="{% url 'newsletter:message_create' %}" type="button" class="col-4 my-3 btn btn-outline-success">Создать сообщение</a>
<table class="table" cellpadding="10" border="1" width="100%">
    <col width="40%">
    <col width="60%">
    <thead>
    <tr>
        <th scope="col">Тема письма</th>
        <th scope="col">Содержание</th>
    </tr>
    </thead>
</table>
{% for object in object_list %}
<table class="table" cellpadding="10" border="1" width="100%">
    <col width="40%">
    <col width="60%">
    <tbody>
    <tr>
        <td><a href="{% url 'newsletter:message_detail' object.pk %}">{{object.message_title}}</a></td>
        <td>{{object.message_content|slice:100}}</td>
    </tr>
    </tbody>
</table>
{% endfor %}
</body>
{% endblock %}