article/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from article.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView
from article.apps import ArticleConfig

app_name = ArticleConfig.name

urlpatterns = [
    path('articles/create/', ArticleCreateView.as_view(), name="create_article"),
    path('articles/update/<int:pk>/', ArticleUpdateView.as_view(), name="update_article"),
    path('articles/', ArticleListView.as_view(), name="articles"),
    path('articles/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name="article_detail"),
    path('articles/delete/<int:pk>/', ArticleDeleteView.as_view(), name="delete_article"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('newsletter.urls', 'newsletter'), namespace='newsletter')),
    path('', include(('article.urls', 'article'), namespace='article')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
app_name = UsersConfig.name

from django.urls import path
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView, UsersListView, \
    toggle_activiti

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='token'),
    path('reset-password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('list/', UsersListView.as_view(), name='user_list'),
    path('toggle_activiti/<int:pk>', toggle_activiti, name='toggle_activiti')

]

article/models.py
from django.db import models

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='articles/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    view_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              **NULLABLE, verbose_name='Автор')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

article/forms.py
from django import forms
from django.forms import BooleanField

from article.models import Article


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ArticleManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Article
        exclude = ('created_at', 'view_count', 'owner',)

article/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from article.forms import ArticleManagerForm
from article.models import Article
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from newsletter.services import get_article_list_from_cache


class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'article.add_article'
    model = Article
    form_class = ArticleManagerForm
    success_url = reverse_lazy('article:articles')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'article.change_article'
    model = Article
    form_class = ArticleManagerForm

    def get_success_url(self):
        return reverse('article:article_detail', args=[self.kwargs.get('pk')])


class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'article.delete_article'
    model = Article
    success_url = reverse_lazy('article:articles')


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        return get_article_list_from_cache()


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object

article/templates/article/article_confirm_delete.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Хотите удалить статью: <i>{{object.title}}</i></h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                        <a href="{% url 'article:articles' %}" type="button" class="btn btn-outline-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

article/templates/article/article_detail.html
{% extends 'newsletter/base.html' %}
{% load my_tags user_tags %}
{% block content %}
<div class="row text-center">
    <div class="col-12">
        <div class="card mt-4 mb-4 box-shadow">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">{{ article.title }}</h3>
            </div>
            <div class="card-body">
                <img src="{{ article.preview|mymedia }}" height="200" class="img">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{ article.content }}</li>
                </ul>
                <p>Автор: {{ object.owner.name|default:'аноним' }}</p>
                <p>Добавлена: {{ object.created_at }}</p>
                <p>Количество просмотров: {{ object.view_count }}</p>
                {% if user|is_content_manager or user.is_superuser or user == object.owner %}
                <a href="{% url 'article:update_article' object.pk %}" type="button"
                   class="btn btn-outline-primary">Редактировать</a>
                <a href="{% url 'article:delete_article' object.pk %}" type="button"
                   class="btn btn-outline-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

article/templates/article/article_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    {% if object %}
                    <h4 class="my-0 font-weight-normal">Редактировать статью</h4>
                    {% else %}
                    <h4 class="my-0 font-weight-normal">Создание статьи</h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {{form.as_p}}
                        {% csrf_token %}
                        {% if object %}
                        <button type="submit" class="btn btn-outline-primary form-control">Сохранить</button>
                        {% else %}
                        <button type="submit" class="btn btn-outline-primary form-control">Добавить</button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

article/templates/article/article_list.html
{% extends 'newsletter/base.html' %}
{% load my_tags %}
{% block content %}
 <h1 class="my-0 mb-4 font-weight-normal">Статьи</h1>
{% if perms.article.add_article %}
<a href="{% url 'article:create_article' %}" class="col-4 btn btn-outline-success mb-3">Добавить статью</a>
{% endif %}
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-5">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">{{ object.title }}</h5>
            </div>
            <div class="card-body">
                <img src="{{ object.preview|mymedia }}" height="111" class="img-thumbnail">
                <span class="textarea">{{ object.content|slice:50 }}</span>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                </ul>
                <a href="{% url 'article:article_detail' object.pk %}" type="button" class="btn btn-outline-success form-control">Читать</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}