config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('newsletter.urls', 'newsletter'), namespace='newsletter')),
    path('', include(('article.urls', 'article'), namespace='article')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
app_name = UsersConfig.name

from django.urls import path
from users.views import UserCreateView, email_verification, UserPasswordResetView, ProfileView, UsersListView, \
    toggle_activiti

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='token'),
    path('reset-password/', UserPasswordResetView.as_view(), name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('list/', UsersListView.as_view(), name='user_list'),
    path('toggle_activiti/<int:pk>', toggle_activiti, name='toggle_activiti')

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email', help_text='введите адрес электронной почты')
    name = models.CharField(max_length=100, verbose_name='имя')
    phone = models.CharField(max_length=35, **NULLABLE, verbose_name='телефон')
    country = models.CharField(max_length=100, **NULLABLE, verbose_name='страна')
    avatar = models.ImageField(upload_to='users/avatar/', default='users/avatar/user_avatar_default.jpg', **NULLABLE, verbose_name='аватар')

    token = models.CharField(max_length=100, verbose_name='token', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            (
                "block_the_user",
                "Can block the user"
            ),
            (
                "view_all_users",
                "Can view all users"
            )
        ]
        

users/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, UserChangeForm
from django import forms
from django.forms import BooleanField
from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserPasswordResetForm(StyleFormMixin, PasswordResetForm):
    pass


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'phone', 'country', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserManagerProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('is_active',)

users/views.py
import secrets
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView
from users.forms import UserRegisterForm, UserPasswordResetForm, UserProfileForm
from users.models import User
from config.settings import DEFAULT_FROM_EMAIL
from users.service import generate_password


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Здравствуйте, для подтверждения регистрации перейдите по ссылке {url}',
            from_email=DEFAULT_FROM_EMAIL,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserPasswordResetView(PasswordResetView):
    model = User
    form_class = UserPasswordResetForm
    template_name = 'users/password_reset_form.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if self.request.method == 'POST':
            user_email = self.request.POST.get('email')
            user = User.objects.filter(email=user_email).first()
            if user:
                new_password = generate_password(16)
                user.set_password(new_password)
                user.save()
                try:
                    send_mail(
                            subject="Восстановление пароля на сайте 'Рассылка'",
                            message=f"Здравствуйте!"
                            f"Ваш пароль для доступа на сайт 'Рассылка' изменен:\n"
                            f"Данные для входа:\n"
                            f"Email: {user_email}\n"
                            f"Пароль: {new_password}",
                            from_email=DEFAULT_FROM_EMAIL,
                            recipient_list=[user.email]
                            )
                except Exception:
                    print(f'Ошибка при отправке на почту {user_email}')
                return HttpResponseRedirect(reverse('users:login'))

        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/user_edit_form.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UsersListView(PermissionRequiredMixin, ListView):
    """ Просмотр списка рассылок """
    model = User
    permission_required = "users.view_all_users"

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if user.is_superuser:
            return super().get_queryset(*args, **kwargs).exclude(pk=self.request.user.pk)
        return super().get_queryset(*args, **kwargs).exclude(pk=self.request.user.pk).exclude(
            is_superuser=True)


@permission_required('users.block_the_user')
def toggle_activiti(request, pk):
    """Контроллер изменения статуса пользователя"""
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse('users:user_list'))

users/templates/users/password_reset_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
<div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Восстановление пароля</h4>
                </div>
                <div class="card-body">
                        {{form.as_p}}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            Отправить пароль
                        </button>
                </div>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_edit_form.html
{% extends 'newsletter/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
<div class="col-8">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Профиль пользователя</h4>
                </div>
                <div class="card-body">
                        {{form.as_p}}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block btn-outline-primary form-control">
                            Сохранить
                        </button>
                </div>
            </div>
        </div>
        <div class="col-4">
            <img src= "{{ user.avatar|mymedia }}" height="400" class="img">
        </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Форма регистрации</h4>
                </div>
                <div class="card-body">
                        {{form.as_p}}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            Зарегистрироваться
                        </button>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<body>
<h1>Список пользователей</h1>

<table class="table" cellpadding="10" border="1" width="100%">
    <col width="30%">
    <col width="40%">
    <col width="30%">
    <thead>
    <tr>
        <th scope="col">Имя</th>
        <th scope="col">Электронный адрес</th>
        <th scope="col">Статус</th>
    </tr>
    </thead>
</table>
{% for object in object_list %}
<table class="table" cellpadding="10" border="1" width="100%">
    <col width="30%">
    <col width="40%">
    <col width="30%">
    <tbody>
    <tr>
        <td>{{object.name}}</td>
        <td><a href="{% url 'users:profile' %}">{{object.email}}</a></td>
        {% if perms.users.block_the_user or user.is_superuser %}
          {% if object.is_active %}
          <td><a href="{% url 'users:toggle_activiti' object.pk %}" class="btn btn-sm btn-outline-danger">Деактивировать</a></td>
          {% else %}
          <td><a href="{% url 'users:toggle_activiti' object.pk %}" class="btn btn-sm btn-outline-success">Активировать</a></td>
          {% endif %}
        {% endif %}
    </tr>
    </tbody>
</table>
{% endfor %}
</body>
{% endblock %}